language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
    pip install codecov
  - python3 setup.py install
# command to run tests
script: make test

after_success:
    codecov
